# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore Nugets
      run: dotnet restore ./src/GraphiGrade.sln
    - name: Build
      run: dotnet build ./src/GraphiGrade.sln --no-restore --configuration Release
    - name: Unit Tests
      run: dotnet test ./tests/GraphiGrade.Tests.UnitTests/GraphiGrade.Tests.UnitTests.csproj --no-build --verbosity normal --configuration Release --logger "trx;LogFileName=TestResults.trx"  --collect:"XPlat Code Coverage"
    - name: Component Tests
      run: dotnet test ./tests/GraphiGrade.Tests.ComponentTests/GraphiGrade.Tests.ComponentTests.csproj --no-build --verbosity normal --configuration Release   
    - name: Code Coverage
      uses: coverallsapp/github-action@v2
      with:
        file: './tests/GraphiGrade.Tests.UnitTests/TestResults/**/coverage.cobertura.xml'
